'use client';
import {useEffect,useState} from 'react';
import {api,date,json} from '@/components/api';
const iso=(v:string)=>new Date(v).toISOString();
const local=(v:string)=>{const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const newOlympiad=()=>({type:'SCHOOL',title:'',description:'',rules:'',status:'draft',registration_start:new Date().toISOString(),registration_end:new Date(Date.now()+7*86400000).toISOString(),allowed_classes:[7,8,9,10,11],ranking_visible:false});
const newStage=()=>({title:'',kind:'qualifying',starts_at:new Date().toISOString(),ends_at:new Date(Date.now()+86400000).toISOString(),duration_minutes:120});
const newTask=()=>({title:'',statement:'',input_description:'',output_description:'',constraints:'',difficulty:'normal',time_limit:2,memory_limit:128,points:100,tests:[{input:'',expected:'',public:true},{input:'',expected:'',public:false}]});
export default function Admin(){
 const [items,setItems]=useState<any[]>([]),[oid,setOid]=useState(''),[tab,setTab]=useState('dashboard'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[data,setData]=useState<any>(null),[stages,setStages]=useState<any[]>([]),[sid,setSid]=useState(''),[q,setQ]=useState(''),[level,setLevel]=useState(''),[form,setForm]=useState<any>(null),[editId,setEditId]=useState(''),[authorized,setAuthorized]=useState(false),[recoverySid,setRecoverySid]=useState('');
 async function loadOlympiads(){const d=await api('/admin/olympiads');setItems(d);setOid(old=>old||d[0]?.id||'');}
 useEffect(()=>{api('/profile').then(p=>{if(p.user.role!=='admin')throw new Error('Требуются права администратора');setAuthorized(true);loadOlympiads().catch(e=>setError(e.message));}).catch(e=>setError(e.message));},[]);
 const o=items.find(o=>o.id===oid);
 async function load(){if(!oid)return;setError('');try{if(tab==='settings'){setForm({...o});return;}if(tab==='stages'){const s=await api('/admin/olympiads/'+oid+'/stages');setStages(s);setData(s);return;}if(tab==='tasks'){const s=await api('/admin/olympiads/'+oid+'/stages');setStages(s);const selected=sid&&s.some((s:any)=>s.id===sid)?sid:s[0]?.id;setSid(selected||'');setData(selected?await api('/admin/stages/'+selected+'/tasks'):[]);return;}const path=tab==='audit'?'/admin/audit':'/admin/olympiads/'+oid+'/'+tab+(tab==='participants'?`?q=${encodeURIComponent(q)}${level?'&level='+level:''}`:'');setData(await api(path));if(tab==='participants')setStages(await api('/admin/olympiads/'+oid+'/stages'));}catch(e:any){setError(e.message);}}
 useEffect(()=>{setForm(null);setEditId('');setData(null);load();},[oid,tab,sid,q,level]);
 function change(k:string,v:any){setForm((old:any)=>({...old,[k]:v}));}
 async function save(kind:string){setError('');setNotice('');try{let path='',body:any={...form};delete body.id;
 if(kind==='olympiad'){path=editId?'/admin/olympiads/'+editId:'/admin/olympiads';}
 if(kind==='stage'){delete body.olympiad_id;path=editId?'/admin/stages/'+editId:'/admin/olympiads/'+oid+'/stages';}
 if(kind==='task'){delete body.olympiad_id;delete body.stage_id;body.tests=body.tests.map(({input,expected,public:p}:any)=>({input,expected,public:p}));path=editId?'/admin/tasks/'+editId:'/admin/stages/'+sid+'/tasks';}
 if(kind==='participant'){body={status:form.status,organization:form.user.organization,school_class:form.school_class,course:form.course,group:form.group};path='/admin/participants/'+editId;}
 await api(path,{method:editId?'PUT':'POST',body:json(body)});setNotice('Изменения сохранены');setForm(null);setEditId('');if(kind==='olympiad')await loadOlymppiadsSafe();await load();}catch(e:any){setError(e.message);}}
 async function loadOlymppiadsSafe(){await loadOlympiads();}
 function field(k:string,label:string,type='text'){return <label key={k}>{label}{type==='textarea'?<textarea value={form[k]||''} onChange={e=>change(k,e.target.value)}/>:<input type={type} required value={type==='datetime-local'?local(form[k]):form[k]??''} onChange={e=>change(k,type==='datetime-local'?iso(e.target.value):type==='number'?Number(e.target.value):e.target.value)}/>}</label>;}
 const tabs=[['dashboard','Обзор'],['settings','Настройки'],['participants','Участники'],['stages','Этапы'],['tasks','Задания'],['submissions','Решения'],['events','Античит'],['ranking','Рейтинг'],['audit','Аудит']];
 return <main className="container"><div className="eyebrow">Панель управления</div><h1>Администрирование</h1>{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}{authorized&&<><div className="row"><select style={{maxWidth:450}} value={oid} onChange={e=>{setData(null);setForm(null);setOid(e.target.value);setSid('');setLevel('');}}>{items.map(o=><option key={o.id} value={o.id}>{o.type==='SCHOOL'?'Школьники':'СПО'} · {o.title}</option>)}</select><button className="btn" onClick={()=>{setTab('new');setForm(newOlympiad());setEditId('');}}>+ Создать олимпиаду</button></div><div className="tabs">{tabs.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>{setData(null);setForm(null);setEditId('');setTab(key);}}>{label}</button>)}</div>
 {tab==='dashboard'&&data&&<div className="stats">{Object.entries(data).map(([k,v])=><div className="stat" key={k}><span className="muted small">{({registered:'Зарегистрировано',course_1:'Студентов 1 курса',course_2:'Студентов 2 курса',started:'Начали этап',finished:'Завершили этап',submissions:'Решений',violations:'Событий античита'} as Record<string,string>)[k]}</span><strong>{String(v)}</strong></div>)}</div>}
 {(tab==='settings'||tab==='new')&&form&&<form className="card formgrid" onSubmit={e=>{e.preventDefault();if(tab==='settings')setEditId(oid);saveOlympiad();}}><h2 className="full">Настройки олимпиады</h2><label>Тип<select value={form.type} onChange={e=>change('type',e.target.value)}><option>SCHOOL</option><option>SPO</option></select></label><label>Статус<select value={form.status} onChange={e=>change('status',e.target.value)}>{['draft','scheduled','active','finished'].map(s=><option key={s}>{s}</option>)}</select></label>{field('title','Название')}{field('description','Описание','textarea')}{field('registration_start','Начало регистрации','datetime-local')}{field('registration_end','Окончание регистрации','datetime-local')}<label>Допустимые классы (через запятую)<input value={form.allowed_classes.join(',')} onChange={e=>change('allowed_classes',e.target.value.split(',').map(Number))}/></label><label className="check"><input type="checkbox" checked={form.ranking_visible} onChange={e=>change('ranking_visible',e.target.checked)}/>Показывать рейтинг</label><div className="full">{field('rules','Правила (Markdown)','textarea')}</div><button className="btn full">Сохранить</button></form>}
 {tab==='participants'&&<><div className="row"><label>Поиск<input value={q} onChange={e=>setQ(e.target.value)} placeholder="ФИО, email, организация"/></label><label>Класс / курс<select value={level} onChange={e=>setLevel(e.target.value)}><option value="">Все</option>{(o?.type==='SCHOOL'?o.allowed_classes:[1,2]).map((n:number)=><option key={n}>{n}</option>)}</select></label><a className="btn secondary" href={'/api/admin/olympiads/'+oid+'/export'}>Экспорт CSV</a><a className="btn secondary" href={'/api/admin/olympiads/'+oid+'/export?format=xlsx'}>Экспорт XLSX</a></div><div className="card spaced tablewrap"><table><thead><tr><th>ФИО</th><th>Организация</th><th>Класс / курс</th><th>Статус</th><th>Действия</th></tr></thead><tbody>{(Array.isArray(data)?data:[]).map((r:any)=><tr key={r.id}><td>{r.user.last_name} {r.user.first_name}<br/>{r.user.email}</td><td>{r.user.organization}</td><td>{r.school_class||r.course}</td><td>{r.status}</td><td><button className="btn secondary" onClick={()=>{setEditId(r.id);setForm(r);}}>Редактировать</button><button className="btn secondary" onClick={async()=>{try{const [events,solutions]=await Promise.all([api('/admin/olympiads/'+oid+'/events'),api('/admin/olympiads/'+oid+'/submissions')]);setNotice(JSON.stringify({events:events.filter((e:any)=>e.participant_id===r.id),submissions:solutions.filter((s:any)=>s.user_id===r.user_id)},null,2));}catch(e:any){setError(e.message);}}}>История</button></td></tr>)}</tbody></table></div>{form&&<form className="card formgrid spaced" onSubmit={e=>{e.preventDefault();save('participant');}}><label>Статус<select value={form.status} onChange={e=>change('status',e.target.value)}><option value="registered">Зарегистрирован</option><option value="blocked">Заблокирован</option><option value="disqualified">Дисквалифицирован</option></select></label><label>Организация<input value={form.user.organization} onChange={e=>change('user',{...form.user,organization:e.target.value})}/></label>{field(o.type==='SCHOOL'?'school_class':'course',o.type==='SCHOOL'?'Класс':'Курс','number')}{o.type==='SPO'&&field('group','Группа')}<button className="btn full">Сохранить</button><label>Восстановление сессии этапа<select value={recoverySid} onChange={e=>setRecoverySid(e.target.value)}><option value="">Выберите этап</option>{stages.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><button type="button" className="btn secondary" disabled={!recoverySid} onClick={async()=>{try{const r=await api('/admin/participants/'+editId+'/reset-session/'+recoverySid,{method:'POST'});setNotice(r.message+'; deadline сохранён');}catch(e:any){setError(e.message);}}}>Освободить сессию</button></form>}</>}
 {tab==='stages'&&<><button className="btn" onClick={()=>{setEditId('');setForm(newStage());}}>+ Добавить этап</button><div className="grid2 spaced">{(Array.isArray(data)?data:[]).map((s:any)=><div className="card" key={s.id}><h3>{s.title}</h3><p>{date(s.starts_at)} — {date(s.ends_at)}</p><p>{s.duration_minutes} минут</p><button className="btn secondary" onClick={()=>{setEditId(s.id);setForm(s);}}>Изменить</button></div>)}</div>{form&&<form className="card formgrid spaced" onSubmit={e=>{e.preventDefault();save('stage');}}>{field('title','Название')}<label>Тип этапа<select value={form.kind} onChange={e=>change('kind',e.target.value)}><option value="qualifying">Отборочный</option><option value="main">Основной</option></select></label>{field('starts_at','Начало','datetime-local')}{field('ends_at','Конец','datetime-local')}{field('duration_minutes','Продолжительность, минут','number')}<button className="btn">Сохранить этап</button></form>}</>}
 {tab==='tasks'&&<><div className="row"><label>Этап<select value={sid} onChange={e=>setSid(e.target.value)}>{stages.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><button className="btn" disabled={!sid} onClick={()=>{setEditId('');setForm(newTask());}}>+ Добавить задание</button></div><div className="grid2 spaced">{(Array.isArray(data)?data:[]).map((t:any)=><div className="card" key={t.id}><h3>{t.title}</h3><p>{t.points} баллов · {t.tests.length} тестов</p><button className="btn secondary" onClick={()=>{setEditId(t.id);setForm(t);}}>Редактировать</button></div>)}</div>{form&&<form className="card formgrid spaced" onSubmit={e=>{e.preventDefault();save('task');}}>{field('title','Название')}{field('difficulty','Сложность')}<div className="full">{field('statement','Условие (Markdown)','textarea')}</div>{field('input_description','Входные данные','textarea')}{field('output_description','Выходные данные','textarea')}{field('constraints','Ограничения')}{field('points','Баллы','number')}{field('time_limit','Лимит времени (1–10 секунд)','number')}{field('memory_limit','Лимит памяти (32–256 МБ)','number')}<h3 className="full">Тесты</h3>{form.tests.map((c:any,i:number)=><div className="card full" key={i}><label className="check"><input type="checkbox" checked={c.public} onChange={e=>change('tests',form.tests.map((v:any,j:number)=>j===i?{...v,public:e.target.checked}:v))}/>Публичный пример</label><div className="grid2">{['input','expected'].map(k=><label key={k}>{k==='input'?'Вход':'Ожидаемый вывод'}<textarea value={c[k]} onChange={e=>change('tests',form.tests.map((v:any,j:number)=>j===i?{...v,[k]:e.target.value}:v))}/></label>)}</div><button type="button" className="btn secondary spaced" onClick={()=>change('tests',form.tests.filter((_:any,j:number)=>j!==i))}>Удалить тест</button></div>)}<button type="button" className="btn secondary" onClick={()=>change('tests',[...form.tests,{input:'',expected:'',public:false}])}>+ Тест</button><button className="btn">Сохранить задание</button></form>}</>}
 {['submissions','events','ranking','audit'].includes(tab)&&Array.isArray(data)&&<div className="card tablewrap"><table><thead><tr>{(tab==='submissions'?['Дата','Участник','Статус','Баллы','Решение']:tab==='events'?['Дата','Участник','Событие','Уровень','Метаданные']:tab==='ranking'?['Место','Участник','Класс / курс','Баллы']:['Дата','Администратор','Действие','Объект']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.map((r:any)=><tr key={r.id||r.participant_id}>{tab==='submissions'?<><td>{date(r.created_at)}</td><td>{r.user_id}</td><td>{r.status}</td><td>{r.score}</td><td><button className="btn secondary" onClick={async()=>{try{setNotice(JSON.stringify(await api('/submissions/'+r.id),null,2));}catch(e:any){setError(e.message);}}}>Открыть</button></td></>:tab==='events'?<><td>{date(r.timestamp)}</td><td>{r.participant_id}</td><td>{r.event_type}</td><td>{r.severity}</td><td>{JSON.stringify(r.metadata_json)}</td></>:tab==='ranking'?<><td>{r.place}</td><td>{r.name}</td><td>{r.school_class||r.course}</td><td>{r.score}</td></>:<><td>{date(r.created_at)}</td><td>{r.actor_id}</td><td>{r.action}</td><td>{r.target_id}</td></>}</tr>)}</tbody></table></div>}
 </>}</main>;
 async function saveOlympiad(){try{const body={...form};delete body.id;const target=tab==='settings'?oid:editId;await api(target?'/admin/olympiads/'+target:'/admin/olympiads',{method:target?'PUT':'POST',body:json(body)});await loadOlympiads();setNotice('Настройки сохранены');if(tab==='new')setTab('settings');}catch(e:any){setError(e.message);}}
}
