'use client';
import CheckResult from './CheckResult';
import {useState} from 'react';
import {api,json,date,answerStatus} from './api';
export default function AdminSolutions({rows,onRefresh}:{rows:any[];onRefresh:()=>void}){
 const [selected,setSelected]=useState<any>(null),[score,setScore]=useState(0),[feedback,setFeedback]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function open(id:string){setError('');try{const r=await api('/submissions/'+id);setSelected(r);setScore(r.score);setFeedback(r.review_feedback||'');}catch(e:any){setError(e.message);}}
 async function review(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/admin/submissions/'+selected.id+'/review',{method:'POST',body:json({score,feedback})});await open(selected.id);onRefresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <>{error&&<p className="error">{error}</p>}<div className="card tablewrap"><table><thead><tr><th>Дата</th><th>Участник</th><th>Задание</th><th>Статус</th><th>Баллы</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{date(r.created_at)}</td><td>{r.participant_name}</td><td>{r.task_title}</td><td>{answerStatus(r.status)}</td><td>{r.score} / {r.max_points}</td><td><button className="btn secondary" onClick={()=>open(r.id)}>Открыть</button></td></tr>)}</tbody></table></div>{selected&&<section className="card spaced"><div className="row between"><h2>{selected.task.title}</h2><button className="btn secondary" onClick={()=>setSelected(null)}>Закрыть</button></div><h3>Ответ участника</h3><pre className="review-answer">{selected.task.kind==='choice'?selected.task.answer_options[Number(selected.code)]:selected.code}</pre>{selected.task.kind==='text'?<form onSubmit={review}><h3>Критерии оценки</h3><p className="review-answer">{selected.task.rubric||'Критерии не заданы. Оцените ответ по условию задания.'}</p><div className="formgrid"><label>Баллы (0–{selected.task.points})<input type="number" required min={0} max={selected.task.points} value={score} onChange={e=>setScore(Number(e.target.value))}/></label><label>Комментарий участнику<textarea maxLength={5000} value={feedback} onChange={e=>setFeedback(e.target.value)}/></label></div><button className="btn spaced" disabled={busy}>Сохранить оценку</button></form>:<CheckResult result={selected}/>}</section>}</>;
}
