'use client';
import {useEffect,useState} from 'react';
import Markdown from 'react-markdown';
import {api} from './api';
export default function TaskForm({value,onChange,onSave,stageKind,audience}:{value:any;onChange:(key:string,value:any)=>void;onSave:()=>void;stageKind?:string;audience?:'SCHOOL'|'SPO'}){
 const [preview,setPreview]=useState(false),[error,setError]=useState(''),[templateId,setTemplateId]=useState(''),[templates,setTemplates]=useState<any[]>([]);
 useEffect(()=>{api('/admin/task-packs/academy?audience='+(audience||'SPO')).then(pack=>setTemplates(pack.tasks)).catch(e=>setError(e.message));},[audience]);
 const available=templates.filter(t=>!stageKind||t.stage_kind===stageKind),selected=available.find(t=>t.key===templateId)||available[0],kind=value.kind||'code';
 function apply(){if(!selected)return;if((value.title.trim()||value.statement.trim())&&!window.confirm('Заменить введённое задание шаблоном «'+selected.title+'»?'))return;for(const [key,v] of Object.entries(selected)){if(!['chapter','stars','topic','key','stage_kind'].includes(key))onChange(key,v);}onChange('academy_chapter',selected.chapter);setError('');}
 function text(key:string,label:string,hint='',required=false){return <label>{label}<textarea value={value[key]||''} required={required} maxLength={key==='statement'?50000:10000} placeholder={hint} onChange={e=>onChange(key,e.target.value)}/>{hint&&<span className="muted small">{hint}</span>}</label>;}
 function testChange(i:number,key:string,v:any){onChange('tests',value.tests.map((c:any,j:number)=>j===i?{...c,[key]:v}:c));}
 return <form className="card spaced" onSubmit={e=>{e.preventDefault();if(kind==='code'&&!value.tests.length){setError('Добавьте хотя бы один тест.');return;}setError('');onSave();}}><h2>Создание задания</h2><section className="card spaced"><h3>Заполнить готовым заданием</h3><p className="muted small">Шаблоны для выбранного этапа: сюжет, примеры и настройки проверки уже заполнены.</p><label>Задание приключения<select aria-label="Готовое задание" value={selected?.key||''} onChange={e=>setTemplateId(e.target.value)}>{available.map(t=><option key={t.key} value={t.key}>{t.position}. {t.title} · {t.kind==='code'?'Python':t.kind==='choice'?'Выбор ответа':'Развёрнутый ответ'}</option>)}</select></label><button type="button" className="btn secondary spaced" disabled={!selected} onClick={apply}>Заполнить задание</button></section><div className="formgrid spaced"><label>Тип задания<select value={kind} onChange={e=>onChange('kind',e.target.value)}><option value="code">Программа на Python</option><option value="choice">Выбор одного ответа</option><option value="text">Развёрнутый ответ</option></select></label><label>Порядок в этапе<input type="number" min={0} max={1000} value={value.position||0} onChange={e=>onChange('position',Number(e.target.value))}/></label><label>Название<input required maxLength={200} value={value.title} onChange={e=>onChange('title',e.target.value)}/></label><label>Максимум баллов<input type="number" required min={1} max={1000} value={value.points} onChange={e=>onChange('points',Number(e.target.value))}/></label><div className="full">{text('statement','Условие или вопрос','Markdown: заголовки, списки, примеры кода.',true)}<button type="button" className="btn secondary spaced" onClick={()=>setPreview(!preview)}>{preview?'Скрыть предпросмотр':'Посмотреть условие глазами участника'}</button>{preview&&<div className="card markdown spaced"><h3>{value.title}</h3><Markdown>{value.statement}</Markdown></div>}</div></div>
 {kind==='choice'&&<section className="spaced"><h3>Варианты ответа</h3><p className="muted small">Добавьте от 2 до 8 вариантов и отметьте единственный правильный. Проверка автоматическая; участнику доступна одна отправка.</p>{(value.answer_options||[]).map((option:string,i:number)=><div className="row spaced" key={i}><label className="check"><input type="radio" name="correct" required checked={value.correct_option===i} onChange={()=>onChange('correct_option',i)}/>Правильный</label><input aria-label={'Вариант '+(i+1)} required maxLength={1000} value={option} onChange={e=>onChange('answer_options',value.answer_options.map((v:string,j:number)=>i===j?e.target.value:v))}/><button type="button" className="btn secondary" onClick={()=>{onChange('answer_options',value.answer_options.filter((_:string,j:number)=>j!==i));onChange('correct_option',value.correct_option===i?null:value.correct_option>i?value.correct_option-1:value.correct_option);}}>Удалить</button></div>)}<button type="button" className="btn secondary spaced" disabled={(value.answer_options||[]).length>=8} onClick={()=>onChange('answer_options',[...(value.answer_options||[]),''])}>+ Вариант ответа</button></section>}
 {kind==='text'&&<section className="spaced">{text('rubric','Критерии оценки (только для преподавателя)','Например: 20 баллов за объяснение, 20 за пример, 10 за обработку особого случая.')}<p className="muted small">Ответ оценивается вручную в разделе «Решения». Участник отправляет один окончательный ответ; после оценки он увидит баллы и комментарий.</p></section>}
 {kind==='code'&&<><details className="spaced"><summary>Описание ввода, вывода и ограничения</summary><div className="grid2 spaced">{text('input_description','Входные данные')}{text('output_description','Выходные данные')}</div>{text('constraints','Ограничения')}</details><h3 className="spaced">Примеры проверки</h3><button type="button" className="btn secondary" onClick={()=>{if((value.title.trim()||value.statement.trim())&&!window.confirm('Заменить задание учебным примером?'))return;onChange('academy_chapter',null);onChange('title','Сумма двух чисел');onChange('statement','Считайте два целых числа и выведите их сумму. Используйте input() без текстовых приглашений.');onChange('input_description','Два целых числа через пробел.');onChange('output_description','Одно целое число — сумма.');onChange('tests',[{input:'2 3\n',expected:'5\n',public:true},{input:'-10 7\n',expected:'-3\n',public:false}]);}}>Заполнить учебным примером</button><p className="muted small">Вход — данные для программы, ожидаемый вывод — правильный результат. Публичные примеры видны участнику, остальные тесты скрыты.</p>{value.tests.map((c:any,i:number)=><section className="card spaced" key={i}><div className="row between"><strong>Проверка {i+1}</strong><button type="button" className="btn secondary" onClick={()=>onChange('tests',value.tests.filter((_:any,j:number)=>j!==i))}>Удалить тест</button></div><div className="grid2 spaced"><label>Вход<textarea value={c.input} maxLength={100000} onChange={e=>testChange(i,'input',e.target.value)}/></label><label>Ожидаемый вывод<textarea value={c.expected} maxLength={100000} onChange={e=>testChange(i,'expected',e.target.value)}/></label></div><label className="check spaced"><input type="checkbox" checked={c.public} onChange={e=>testChange(i,'public',e.target.checked)}/>Публичный пример</label></section>)}<button type="button" className="btn secondary spaced" disabled={value.tests.length>=50} onClick={()=>onChange('tests',[...value.tests,{input:'',expected:'',public:false}])}>+ Добавить проверку</button><details className="spaced"><summary>Настройки выполнения Python</summary><div className="formgrid spaced"><label>Лимит времени на тест (секунд)<input type="number" min={1} max={10} value={value.time_limit} onChange={e=>onChange('time_limit',Number(e.target.value))}/></label><label>Лимит памяти (МБ)<input type="number" min={32} max={256} value={value.memory_limit} onChange={e=>onChange('memory_limit',Number(e.target.value))}/></label></div></details></>}{error&&<div className="error">{error}</div>}<button className="btn spaced">Сохранить задание</button></form>;
}
