'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api,date,statusLabel} from '@/components/api';
import {academyChapters} from '@/lib/academy';
type Olympiad={id:string;type:string;title:string;description:string;status:string;registration_start:string;registration_end:string;stages:{kind:string;starts_at:string}[]};
export default function Home(){
 const [items,setItems]=useState<Olympiad[]>([]),[error,setError]=useState('');
 useEffect(()=>{api('/olympiads').then(setItems).catch(e=>setError(e.message));},[]);
 return <main className="container academy-home">
  <section className="academy-hero">
   <div className="academy-hero-copy"><span className="academy-kicker"><span/> Сюжетная олимпиада по Python</span><h1>Сбой в Академии<br/><em>Алгоритмов</em><span className="hero-asterisk" aria-hidden="true">✳</span></h1><p>Питония теряет связь. Двери заблокированы. Главный сервер захватил <strong>Null</strong>.<br/>И только твой код может всё исправить.</p><div className="row"><a className="btn academy-cta" href="#olympiads">Принять миссию <span aria-hidden="true">→</span></a><a className="btn secondary" href="#mission-map">Посмотреть главы ↓</a></div><div className="hero-tags"><span>Python 3</span><span>8 глав</span><span>Один город, который ждёт тебя</span></div></div>
   <div className="academy-visual" aria-label="Главный сервер Академии захвачен вирусом Null"><div className="visual-grid"/><div className="server-top row between"><span>ACADEMY / CORE_01</span><span className="signal-error">● Сбой системы</span></div><div className="server-racks" aria-hidden="true">{[0,1,2].map(n=><div className="server-rack" key={n}>{[0,1,2,3,4].map(i=><div className="rack-unit" key={i}><span/><b/><i/></div>)}</div>)}</div><div className="null-label" aria-hidden="true">NULL<span>ACCESS DENIED_</span></div><div className="server-console"><span>&gt; status: city_offline</span><span>&gt; waiting_for: your_code</span><span className="console-ready">&gt; mission: restore_academy<span className="cursor-block"/></span></div><div className="visual-sticker"><strong>ТЫ</strong><span>ученик-программист<br/>последний на связи</span><span aria-hidden="true">→</span></div></div>
  </section>
  <div className="mission-strip"><span>Сначала — код от двери.</span><span>Потом — судьба целого города.</span><strong>Начни с первой строки Python →</strong></div>
  <section className="academy-story" aria-labelledby="story-title"><div><span className="eyebrow">Питония / ночь сбоя</span><h2 id="story-title">Это больше,<br/>чем восемь задач.</h2></div><div><p>Академия Алгоритмов хранит программы, управляющие всем городом. Этой ночью неизвестный вирус Null перепутал данные, отключил транспорт и спрятал главный ключ доступа.</p><p>Ты оказался внутри во время атаки. За каждой дверью — новая задача. Восстанови пропуск, пройди энергетический тоннель, найди серверную и доберись до центрального ядра.</p><span className="story-note">Твои инструменты: логика, Python и любопытство.</span></div></section>
  <section id="mission-map" className="mission-map" aria-labelledby="map-title"><div className="row between"><div><span className="eyebrow">Маршрут ученика</span><h2 id="map-title">Восемь глав. Одна миссия.</h2></div><span className="map-caption">От первой цифры до поиска в графе</span></div><ol className="chapter-grid">{academyChapters.map(ch=><li className="chapter-card" key={ch.chapter}><div className="row between"><span className="chapter-number">{String(ch.chapter).padStart(2,'0')}</span><span className="chapter-stars" aria-label={'Сложность '+ch.stars+' из 5'}>{'★'.repeat(ch.stars)}<span>{'☆'.repeat(5-ch.stars)}</span></span></div><span className="chapter-location">{ch.location}</span><h3>{ch.title}</h3><p>{ch.description}</p><span className="chapter-topic">{ch.topic}</span></li>)}</ol><p className="muted small">Главы идут по сюжету. Во время олимпиады можно решать задачи в любом порядке.</p></section>
  <section id="olympiads" className="academy-registration"><div className="row between"><div><span className="eyebrow">Вход в Академию</span><h2>Выбери свою олимпиаду</h2></div><span className="muted small">Школьники и СПО · отдельные рейтинги</span></div>{error&&<div className="error">{error}</div>}<div className="grid2">{items.map(o=><article className={'card olympcard '+(o.type==='SPO'?'spo':'')} key={o.id}><div className="row between"><span className="badge">{o.type==='SCHOOL'?'Для школьников':'1 и 2 курс СПО'}</span><span className="badge green">{statusLabel[o.status]}</span></div><h2>{o.title}</h2><p className="muted">{o.description}</p><div className="dates"><div><span>Регистрация</span><strong>{date(o.registration_start)} — {date(o.registration_end)}</strong></div>{o.stages.map(s=><div key={s.kind}><span>{s.kind==='main'?'Основной этап':'Отборочный этап'}</span><strong>{date(s.starts_at)}</strong></div>)}</div><div className="row"><Link className="btn" href={'/register/'+o.id}>Зарегистрироваться →</Link><Link className="btn secondary" href={'/olympiads/'+o.id}>Подробнее</Link></div></article>)}</div>{!items.length&&!error&&<p className="muted">Загрузка олимпиад…</p>}<p className="muted small spaced">Здесь показаны опубликованные олимпиады. Приключение Академии появится после того, как организатор откроет регистрацию.</p></section>
  <section className="academy-how"><span className="eyebrow">Как попасть в историю</span><h2>Три шага до первой двери</h2><div className="featuregrid">{[['01','Зарегистрируйся','Выбери олимпиаду, заполни анкету и подтверди почту.'],['02','Начни этап','Открой миссию в личном кабинете. Код можно писать прямо в браузере.'],['03','Восстанови Академию','Проверяй решения на примерах, отправляй их на проверку и двигайся к ядру.']].map(([n,t,d])=><div className="feature" key={n}><span className="chapter-number">{n}</span><h3>{t}</h3><p className="muted small">{d}</p></div>)}</div></section>
  <section className="academy-faq"><span className="eyebrow">Перед стартом</span><h2>Есть вопросы?</h2><details><summary>Нужно ли устанавливать Python?</summary><p>Нет. Решения пишутся в редакторе на сайте и запускаются на сервере. Нужны браузер и доступ к интернету.</p></details><details><summary>Можно ли начать с простой задачи?</summary><p>Да. Сложность глав постепенно растёт: от суммы цифр до поиска пути в графе. Можно возвращаться к задачам и решать их в любом порядке.</p></details><details><summary>Как узнать, что решение правильное?</summary><p>Кнопка «Запустить» проверяет открытые примеры. «Отправить решение» проверяет все тесты и начисляет баллы. Принятое решение получает статус Accepted.</p></details></section>
  <section className="academy-bottom"><span className="eyebrow">Сообщение с аварийного терминала</span><h2>Питония ждёт.<br/>Начни писать код.</h2><a href="#olympiads" className="btn academy-cta">Принять миссию →</a><span className="bottom-code" aria-hidden="true">&gt; your_story.start()</span></section>
 </main>;
}
