'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api,date,statusLabel} from '@/components/api';
type Olympiad={id:string;type:string;title:string;description:string;status:string;registration_start:string;registration_end:string;stages:{kind:string;starts_at:string}[]};
export default function Home(){
 const [items,setItems]=useState<Olympiad[]>([]),[error,setError]=useState('');
 useEffect(()=>{api('/olympiads').then(setItems).catch(e=>setError(e.message));},[]);
 return <main className="container"><section className="hero"><div><div className="eyebrow">Думай · Программируй · Побеждай</div><h1>Твой следующий шаг<br/>в мире <span style={{color:'#3455db'}}>Python</span></h1><p className="muted">Две независимые олимпиады для тех, кто любит решать задачи. Выбери свой путь, проверь знания и открой новые возможности.</p><div className="row"><span className="badge">Python 3</span><span className="badge">Онлайн-формат</span><span className="badge">Автоматическая проверка</span></div></div><div className="codeart"><div className="dots"><i/><i/><i/></div><span style={{color:'#c4b5fd'}}>def</span> next_step(skills):<br/>&nbsp;&nbsp;curiosity = <span style={{color:'#86efac'}}>True</span><br/>&nbsp;&nbsp;<span style={{color:'#c4b5fd'}}>while</span> curiosity:<br/>&nbsp;&nbsp;&nbsp;&nbsp;skills += solve_challenge()<br/>&nbsp;&nbsp;<span style={{color:'#c4b5fd'}}>return</span> your_future</div></section><div className="row between"><h2>Выбери свою олимпиаду</h2><span className="muted small">Отдельные задания и рейтинги</span></div>{error&&<div className="error">{error}</div>}<div className="grid2">{items.map(o=><article className={'card olympcard '+(o.type==='SPO'?'spo':'')} key={o.id}><div className="row between"><span className="badge">{o.type==='SCHOOL'?'Для школьников':'1 и 2 курс СПО'}</span><span className="badge green">{statusLabel[o.status]}</span></div><h2>{o.title}</h2><p className="muted">{o.description}</p><div className="dates"><div><span>Регистрация</span><strong>{date(o.registration_start)} — {date(o.registration_end)}</strong></div>{o.stages.map(s=><div key={s.kind}><span>{s.kind==='main'?'Основной этап':'Отборочный этап'}</span><strong>{date(s.starts_at)}</strong></div>)}</div><div className="row"><Link className="btn" href={'/register/'+o.id}>Зарегистрироваться →</Link><Link className="btn secondary" href={'/olympiads/'+o.id}>Подробнее</Link></div></article>)}</div>{!items.length&&!error&&<p className="muted">Загрузка олимпиад…</p>}<section className="featuregrid">{[['01','Выбери олимпиаду','Школьники и студенты СПО соревнуются отдельно.'],['02','Решай на Python','Пиши код в браузере и проверяй его на примерах.'],['03','Следи за результатами','Автоматическая проверка и свой рейтинг участников.']].map(([n,t,d])=><div className="feature" key={n}><div className="eyebrow">{n}</div><h3>{t}</h3><p className="muted small">{d}</p></div>)}</section></main>
}
