'use client';
import {use,useEffect,useState} from 'react';
import Link from 'next/link';
import {api,json} from '@/components/api';
export default function Register({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);const [o,setO]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/olympiads/'+id).then(setO).catch(e=>setError(e.message));},[id]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));const body:any={...data,olympiad_id:id,consent_data:data.consent_data==='on',consent_rules:data.consent_rules==='on'};if(body.password!==body.confirm_password){setError('Пароли не совпадают');setBusy(false);return;}if(new Date(String(body.birth_date))>=new Date()){setError('Некорректная дата рождения');setBusy(false);return;}if(o.type==='SCHOOL')body.school_class=Number(data.school_class);else body.course=Number(data.course);try{const r=await api('/auth/register',{method:'POST',body:json(body)});setMessage(r.message);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <main className="container"><div className="form"><div className="eyebrow">Регистрация участника</div><h1>{o?.title||'Олимпиада'}</h1><p className="muted">Заполните данные участника. После регистрации подтвердите email.</p>{error&&<div className="error">{error}</div>}{message?<div className="notice">{message} <Link href="/login">Перейти ко входу</Link></div>:o&&<form className="card formgrid" onSubmit={submit}>{[['last_name','Фамилия'],['first_name','Имя'],['middle_name','Отчество (необязательно)'],['birth_date','Дата рождения'],['email','Email'],['phone','Телефон'],['region','Регион'],['city','Населённый пункт'],['organization','Полное название образовательной организации']].map(([name,label])=><label className={name==='organization'?'full':''} key={name}>{label}<input name={name} type={name==='birth_date'?'date':name==='email'?'email':name==='phone'?'tel':'text'} required={name!=='middle_name'} maxLength={name==='organization'?300:150}/></label>)}{o.type==='SCHOOL'?<label>Класс<select name="school_class" required>{o.allowed_classes.map((c:number)=><option key={c} value={c}>{c} класс</option>)}</select></label>:<><label>Курс<select name="course"><option value="1">1 курс</option><option value="2">2 курс</option></select></label><label>Группа (необязательно)<input name="group" maxLength={100}/></label></>}<label>Пароль<input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/><span className="muted small">Не менее 12 символов</span></label><label>Подтверждение пароля<input name="confirm_password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><label className="check full"><input name="consent_data" type="checkbox" required/>Согласен на обработку персональных данных для регистрации, проведения олимпиады и формирования результатов. Организатор должен предоставить свою политику обработки данных до публичного запуска.</label><label className="check full"><input name="consent_rules" type="checkbox" required/><span>Согласен с <Link style={{color:'#3455db'}} href={'/olympiads/'+id+'#rules'}>правилами олимпиады</Link></span></label><button className="btn full" disabled={busy}>{busy?'Отправка…':'Создать аккаунт и зарегистрироваться'}</button><p className="muted full small">Уже есть аккаунт? <Link href="/login">Войдите</Link> и зарегистрируйтесь из личного кабинета.</p></form>}</div></main>
}
